# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0705545dc1d2580d5e18c402359383f11e48d00843f88dec20a4f7ed8f744b4ef38dafd639df27b82fb1685bc9311512010175676da92d9b5a6e955d46924832

test:
  secret_key_base: 747ef12cb7de4b4d27b47df3eec7c3252ffc1b0167ad87c9d3ce846f5aa307f30d2968fb28399542b7244e4d528db8cdbec90b70b2695429ea4319fff6da844f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
